server:
  port: 8088
spring:
  application:
    name: analytics-service
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: analytics-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
